title:            Site Title
description:      Describe your website.

url:              http://www.suomi-romania.fi

timezone:         Europe/Helsinki

exclude:          [Gemfile, Gemfile.lock, README.md, CNAME, bower_components, bower.json, node_modules, package.json]

#markdown:         kramdown

plugins:
  # - jemoji
  
excerpt_separator: <!--more-->

future:           BOOL

